# Date Time analysis

In [3]:
import os
import pandas as pd
import numpy as np

path= r"C:\Users\Lenovo\Desktop\Data Sets\Cars"
os.chdir(path)
os.listdir(path)
df = pd.read_excel("Data and time.xlsx")

In [4]:
df.head()

Transaction.Date
0  2016-08-30 00:00:00
1  2016-08-29 00:00:00
2  2016-08-31 22:45:01
3  2016-08-31 21:50:05
4  2016-08-31 21:29:00

In [8]:
df.dtypes

Transaction.Date    object
dtype: object

In [9]:
df['Date']=pd.to_datetime(df['Transaction.Date'])
df.head()

Transaction.Date                Date
0  2016-08-30 00:00:00 2016-08-30 00:00:00
1  2016-08-29 00:00:00 2016-08-29 00:00:00
2  2016-08-31 22:45:01 2016-08-31 22:45:01
3  2016-08-31 21:50:05 2016-08-31 21:50:05
4  2016-08-31 21:29:00 2016-08-31 21:29:00

In [11]:
df.dtypes

Transaction.Date            object
Date                datetime64[ns]
dtype: object

In [14]:
#Extract Month
df['Month_num_number']=df["Date"].dt.month
df.head()
df['Month_name']=df['Date'].dt.month_name()
df.head()
df['Month_name_abb']=df['Date'].dt.month_name().str.slice(stop=3)
df.head()

Transaction.Date                Date  Month_num_number Month_name  \
0  2016-08-30 00:00:00 2016-08-30 00:00:00                 8     August   
1  2016-08-29 00:00:00 2016-08-29 00:00:00                 8     August   
2  2016-08-31 22:45:01 2016-08-31 22:45:01                 8     August   
3  2016-08-31 21:50:05 2016-08-31 21:50:05                 8     August   
4  2016-08-31 21:29:00 2016-08-31 21:29:00                 8     August   

  Month_name_abb  
0            Aug  
1            Aug  
2            Aug  
3            Aug  
4            Aug

In [18]:
#Extract Days

df['Day']=df['Date'].dt.day
df.head()
df['Day_name']=df['Date'].dt.day_name()
df.head()
df['Day_abb']=df['Date'].dt.day_name().str.slice(stop=3)
df.head()

Transaction.Date                Date  Month_num_number Month_name  \
0  2016-08-30 00:00:00 2016-08-30 00:00:00                 8     August   
1  2016-08-29 00:00:00 2016-08-29 00:00:00                 8     August   
2  2016-08-31 22:45:01 2016-08-31 22:45:01                 8     August   
3  2016-08-31 21:50:05 2016-08-31 21:50:05                 8     August   
4  2016-08-31 21:29:00 2016-08-31 21:29:00                 8     August   

  Month_name_abb  Day   Day_name Day_abb  
0            Aug   30    Tuesday     Tue  
1            Aug   29     Monday     Mon  
2            Aug   31  Wednesday     Wed  
3            Aug   31  Wednesday     Wed  
4            Aug   31  Wednesday     Wed

In [19]:
#For practicing the time now we import Naredra modi tweet||||

#import narendramodi excel first///

In [20]:
import os
import pandas as pd
import numpy as np

path= r"C:\Users\Lenovo\Desktop\Data Sets\Cars"
os.chdir(path)
os.listdir(path)
NM = pd.read_excel("narendramodi_tweets.xlsx")

In [21]:
NM.head(2)

id  retweets_count  favorite_count          created_at  \
0  826000000000000000            1406            4903 2017-01-31 11:00:00   
1  826000000000000000             907            2877 2017-01-31 10:59:00   

                                                text lang  retweeted  \
0  The President's address wonderfully encapsulat...   en      False   
1  Rashtrapati Ji's address to both Houses of Par...   en      False   

   followers_count  friends_count  hashtags_count              description  \
0         26809964           1641               1  Prime Minister of India   
1         26809964           1641               0  Prime Minister of India   

  location                               background_image_url  \
0    India  http://pbs.twimg.com/profile_background_images...   
1    India  http://pbs.twimg.com/profile_background_images...   

               source  
0  Twitter Web Client  
1  Twitter Web Client

In [22]:
##1) Month wise tweets


NM['created_at'].dtypes
NM['Date']=pd.to_datetime(NM['created_at'])
NM.head()
NM['Date'].dtypes

dtype('<M8[ns]')

In [24]:
NM['Month_num_number']=NM['Date'].dt.month

In [25]:
NM1=NM.groupby('Month_num_number').size().reset_index()
NM1

Month_num_number    0
0                  1  238
1                  3  151
2                  4  197
3                  5  286
4                  6  401
5                  7  291
6                  8  339
7                  9  271
8                 10  359
9                 11  214
10                12  240

In [33]:
NM['Hours']=NM['Date'].dt.hour
NM2=NM.groupby('Hours').size().reset_index()
NM2.sort_values(by=0,ascending=False)

Hours    0
14     14  367
13     13  357
10     10  254
15     15  250
12     12  216
2       2  153
16     16  148
11     11  139
9       9  135
7       7  133
6       6  132
5       5  127
1       1  121
8       8  113
3       3  111
17     17   70
4       4   60
0       0   48
19     19   19
18     18   16
20     20   14
21     21    2
22     22    1
23     23    1

In [36]:
NM['Day']=NM["Date"].dt.day
NM.groupby("Day").size().reset_index().head()

Day    0
0    1   76
1    2  106
2    3   90
3    4  129
4    5   79

# PCA

In [37]:
#Dummy Data Set
    
import pandas as pd
import numpy as np
df=pd.DataFrame({'age':[2,4,6] , 'height':[20,40,60], 'wts':[32,34,38],'gender':['M','F','M']})
df

age  height  wts gender
0    2      20   32      M
1    4      40   34      F
2    6      60   38      M

In [38]:
#Predict the gender using other column:

In [40]:
X=df[['age','height','wts']]

In [42]:
evalue,evector=np.linalg.eig(X)
print(evalue)
print(evector)

[ 8.72863617e+01 -1.74814387e-15 -7.28636167e+00]
[[-4.03094953e-01 -9.95037190e-01 -8.99274765e-01]
 [-5.56486180e-01  9.95037190e-02 -2.02633096e-01]
 [-7.26524322e-01  2.31320866e-16  3.87614145e-01]]


In [43]:
pcs=np.dot(X,evector)
pcs

array([[-3.51846918e+01,  6.29204470e-15,  6.55244118e+00],
       [-4.85736540e+01,  5.64446341e-15,  1.47645802e+00],
       [-6.34156648e+01,  5.23747924e-15, -2.82429685e+00]])

In [46]:
import pandas as pd
pcs_df=pd.DataFrame(pcs)
pcs_df

0             1         2
0 -35.184692  6.292045e-15  6.552441
1 -48.573654  5.644463e-15  1.476458
2 -63.415665  5.237479e-15 -2.824297

In [55]:
#Calculate the information given by each PC
var_of_each_pc = pd.DataFrame(pcs_df.var())
print(var_of_each_pc)
Total_var=pcs_df.var().sum()
#Total_var

              0
0  1.994229e+02
1  2.828510e-31
2  2.203089e+01


In [52]:
var_of_each_pc['Percentage']=(round((var_of_each_pc[0]/Total_var),2)*100)
var_of_each_pc

0  Percentage
0  1.994229e+02        90.0
1  2.828510e-31         0.0
2  2.203089e+01        10.0

In [58]:
from pydataset import data

In [59]:
#Step to Follow
iris=data('iris')
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

In [60]:
iris['Species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [61]:
X = iris[['Sepal.Length','Sepal.Width','Petal.Length','Petal.Width']]
Y=iris[['Species']] #my target variable

In [62]:
#Splitting the data into training as testing
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y, test_size=0.2)
len(X_train),len(X_test),len(Y_train),len(Y_test)

(120, 30, 120, 30)

In [63]:
# Standarized the data

from sklearn.preprocessing import StandardScaler

#create a standarized object 

sc1=StandardScaler()


In [64]:
#Fitting this object on my test  and training data

In [65]:
X_train1=sc1.fit_transform(X_train)
X_test1=sc1.fit_transform(X_test)

In [66]:
#Creating the Model

from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier()

#Fitting the object on training data

model1=classifier.fit(X_train1,Y_train)

C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  if __name__ == '__main__':


In [67]:
#Predicting on test data
Y_test['Pred_Species'] = model1.predict(X_test1)

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [68]:
Y_test.head()

Species Pred_Species
61  versicolor   versicolor
50      setosa       setosa
8       setosa   versicolor
58  versicolor   versicolor
18      setosa   versicolor

In [69]:
pd.crosstab(Y_test.Species,Y_test.Pred_Species)

Pred_Species  setosa  versicolor  virginica
Species                                    
setosa            11           6          0
versicolor         0           3          5
virginica          0           0          5

In [70]:
Accuracy=y=(11+3+5)/30
Accuracy

0.6333333333333333